# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c87edc924d515607c7f0d68f4c65208593c65681ed1b6ccd8ccd132e876f6e6b407c025b515a6c43d67d5546f7137e328a8d078ec4757bb94f1e3981bf912061

test:
  secret_key_base: 36640bfdffd9bbe2584d70998464e9cd2ae4564038d77351495bcea21246d44577c7d483c949d22efd79e3a44b92e43fe03dd3184fe95bfbdfcdccd245816d70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
